### ISSUE TITLE
Simple Example using both dia_router and dia_body

### ISSUE THREAD

**Issue by marktyers** [unger1984/dia_body#1]
Hi
I've been trying to get your example code working. If I provide the request body as a JSON string how do I access this data in a route? The sample code you provide outputs nothing to the browser, I was expecting to see the data in the ctx.parsed property.

Perhaps some documentation would make things easier to understand.

When I try to combine this with dia_router the code won't run, see my attempt below.

```dart
import 'dart:io';

import 'package:dia/dia.dart' as dia;
import 'package:dia_router/dia_router.dart' as dia_router;
import 'package:dia_body/dia_body.dart';

/// Custom Context with Routing mixin
class ContextWithRouting extends dia.Context with dia_router.Routing, ParsedBody {
  ContextWithRouting(HttpRequest request) : super(request);
}

main() async {

  final app = dia.App((req)=>ContextWithRouting(req));

  app.use(body());
  
  final router = dia_router.Router('');

  router.post('/', (ctx,next) async {
    ctx.body = ''' 
      query=${ctx.query}
      parsed=${ctx.parsed}
      files=${ctx.files}
    ''';
  });
  
  app.use(router.middleware);

  await app.listen('0.0.0.0', 8080);
  print('web server running');

}
```

When I run this I get the following output:

```
post.dart:27:18: Error: The getter 'parsed' isn't defined for the class 'Routing'.
 - 'Routing' is from 'package:dia_router/src/routing_mixin.dart' ('../../.pub-cache/hosted/pub.dartlang.org/dia_router-0.1.6/lib/src/routing_mixin.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'parsed'.
    parsed=${ctx.parsed}
                 ^^^^^^
post.dart:28:17: Error: The getter 'files' isn't defined for the class 'Routing'.
 - 'Routing' is from 'package:dia_router/src/routing_mixin.dart' ('../../.pub-cache/hosted/pub.dartlang.org/dia_router-0.1.6/lib/src/routing_mixin.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'files'.
    files=${ctx.files}
```

Any help would be appreciated.

**Comment by unger1984** [comment]
Hi!

Your code will be that:

```dart
import 'dart:io';

import 'package:dia/dia.dart' as dia;
import 'package:dia_body/dia_body.dart';
import 'package:dia_router/dia_router.dart' as dia_router;

/// Custom Context with Routing mixin
class ContextWithRouting extends dia.Context
    with dia_router.Routing, ParsedBody {
  ContextWithRouting(HttpRequest request) : super(request);
}

main() async {
  final app = dia.App<ContextWithRouting>((req) => ContextWithRouting(req));

  app.use(body());

  final router = dia_router.Router<ContextWithRouting>('/perfix');

  router.post('/', (ctx, next) async {
    ctx.body = ''' 
    query=${ctx.query}
    parsed=${ctx.parsed}
    files=${ctx.files}
    ''';
  });

  app.use(router.middleware);

  await app.listen('0.0.0.0', 8080);
  print('web server running');
}
```

**Comment by marktyers** [comment]
That fixes the errors, thanks for the super fast reply, you star! How do I get access to the JSON string in the request body. I'm setting the request header Content-Type to application/json and the request body looks like this:

```json
{
  "name": "Mark"
}
```

This data is not being printed in the response. How do I access this request body in the route please?

Many thanks in advance.

**Comment by unger1984** [comment]
Here is an example of testing your code through Postman

<img width="662" alt="image" src="https://user-images.githubusercontent.com/1415693/123510136-7ad7fd00-d682-11eb-9f0a-1398c706201f.png">

As you can see, the passed json is contained in the field  parsed={test: 1111}

**Comment by marktyers** [comment]
Thanks however here is the output of the code when I run it:
<img width="870" alt="Screenshot 2021-06-26 at 11 41 32" src="https://user-images.githubusercontent.com/207904/123510476-be773a80-d673-11eb-82f9-7c03cf7571e5.png">

**Comment by unger1984** [comment]
Use this code https://github.com/unger1984/dia_body/issues/1#issuecomment-868980911

**Comment by marktyers** [comment]
That's the code I'm running. It won't show me the request body.
<img width="886" alt="Screenshot 2021-06-26 at 13 06 02" src="https://user-images.githubusercontent.com/207904/123512419-4c0c5780-d67f-11eb-90b3-5dc7080b0f04.png">

Perhaps its an issue with the version of Dart?

Dart SDK version: 2.12.2 (stable) (Unknown timestamp) on "linux_x64"
